'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { storage } from '@/lib/utils';

type Lang = 'fr' | 'en';

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

/* ─── Translations ───────────────────────────────── */
const translations: Record<Lang, Record<string, string>> = {
  fr: {
    /* Nav */
    'nav.home':         'Accueil',
    'nav.events':       'Événements',
    'nav.restaurants':  'Restaurants & Nightlife',
    'nav.cinema':       'Cinéma & Culture',
    'nav.discover':     'Découvrir Bangui',
    'nav.practical':    'Infos Pratiques',
    'nav.hotels':       'Hôtels',
    'nav.cars':         'Location Voiture',
    'nav.talents':      'Talents & Inspirations',
    'nav.gallery':      'Galerie',
    'nav.shop':         'Boutique',
    'nav.contact':      'Contact',
    'nav.admin':        'Admin',

    /* Home hero */
    'hero.tagline':     'Le meilleur de Bangui',
    'hero.subtitle':    'Événements, restaurants, culture et nightlife à Bangui, République Centrafricaine',
    'hero.cta.discover':'Découvrir Bangui',
    'hero.cta.events':  'Explorer les événements',
    'hero.cta.book':    'Réserver une expérience',

    /* Sections */
    'section.events.title':      'Événements à venir',
    'section.events.subtitle':   'Ne manquez aucun événement',
    'section.restaurants.title': 'Restaurants & Nightlife',
    'section.restaurants.subtitle': 'Les meilleures adresses de Bangui',
    'section.talents.title':     'Talents & Inspirations',
    'section.talents.subtitle':  'Rencontrez les personnalités de Bangui',
    'section.gallery.title':     'Galerie',
    'section.gallery.subtitle':  'Les plus beaux moments',
    'section.articles.title':    'Derniers articles',
    'section.articles.subtitle': 'Découvrez notre magazine',
    'section.newsletter.title':  'Restez connecté',
    'section.newsletter.subtitle':'Recevez nos meilleures recommandations',
    'section.newsletter.cta':    'S\'abonner',
    'section.newsletter.placeholder': 'Votre email',

    /* General */
    'general.noContent':  'Aucun contenu disponible',
    'general.comingSoon': 'Revenez bientôt pour du nouveau contenu',
    'general.seeAll':     'Voir tout',
    'general.learnMore':  'En savoir plus',
    'general.bookNow':    'Réserver',
    'general.loading':    'Chargement...',
    'general.error':      'Une erreur est survenue',
    'general.noResults':  'Aucun résultat',
    'general.free':       'Gratuit',
    'general.from':       'À partir de',
    'general.at':         'à',
    'general.by':         'par',
    'general.on':         'le',
    'general.in':         'à',
    'general.readMore':   'Lire la suite',
    'general.share':      'Partager',
    'general.filter':     'Filtrer',
    'general.all':        'Tout',
    'general.featured':   'À la une',
    'general.new':        'Nouveau',
    'general.sold_out':   'Complet',
    'general.limited':    'Édition limitée',
    'general.save':       'Enregistrer',
    'general.cancel':     'Annuler',
    'general.delete':     'Supprimer',
    'general.edit':       'Modifier',
    'general.add':        'Ajouter',
    'general.search':     'Rechercher',
    'general.close':      'Fermer',
    'general.back':       'Retour',
    'general.next':       'Suivant',
    'general.prev':       'Précédent',
    'general.submit':     'Envoyer',
    'general.confirm':    'Confirmer',
    'general.success':    'Succès !',

    /* Events */
    'events.title':        'Événements',
    'events.category.all': 'Tous',
    'events.rsvp':         'RSVP',
    'events.tickets':      'Billets',
    'events.countdown':    'Compte à rebours',
    'events.past':         'Événement passé',
    'events.today':        'Aujourd\'hui',
    'events.search':       'Rechercher un événement...',
    'events.found':        'événement(s) trouvé(s)',

    /* Category filters */
    'cat.all':              'Tous',
    'cat.concerts':         'Concerts',
    'cat.festivals':        'Festivals',
    'cat.cinema':           'Cinéma',
    'cat.poolParties':      'Pool Parties',
    'cat.jazzNights':       'Jazz Nights',
    'cat.sports':           'Sports',
    'cat.exhibitions':      'Expositions',
    'cat.restaurantOpenings':'Restaurants',
    'cat.restaurant':       'Restaurants',
    'cat.bar':              'Bars',
    'cat.rooftop':          'Rooftops',
    'cat.lounge':           'Lounges',
    'cat.nightclub':        'Nightlife',
    'cat.cafe':             'Cafés',
    'cat.streetFood':       'Street Food',
    'cat.fastFood':         'Fast Food',
    'cat.tshirts':          'T-Shirts',
    'cat.caps':             'Casquettes',
    'cat.toteBags':         'Tote Bags',
    'cat.glassware':        'Verrerie',
    'cat.accessories':      'Accessoires',
    'cat.limitedEditions':  'Éditions Limitées',
    'cat.events':           'Événements',
    'cat.food':             'Gastronomie',
    'cat.culture':          'Culture',
    'cat.video':            'Vidéos',
    'cat.artist':           'Artistes',
    'cat.musician':         'Musiciens',
    'cat.entrepreneur':     'Entrepreneurs',
    'cat.influencer':       'Influenceurs',
    'cat.chef':             'Chefs',
    'cat.creator':          'Créateurs',

    /* Restaurants */
    'restaurants.reserve':    'Réserver une table',
    'restaurants.hours':      'Horaires',
    'restaurants.menu':       'Menu',
    'restaurants.gallery':    'Photos',
    'restaurants.reviews':    'Avis',
    'restaurants.call':       'Appeler',
    'restaurants.directions': 'Itinéraire',
    'restaurants.search':     'Rechercher un restaurant...',
    'restaurants.allAddresses':'Toutes les adresses',

    /* Shop */
    'shop.cart':           'Panier',
    'shop.addToCart':      'Ajouter au panier',
    'shop.checkout':       'Commander',
    'shop.total':          'Total',
    'shop.quantity':       'Quantité',
    'shop.size':           'Taille',
    'shop.color':          'Couleur',
    'shop.empty':          'Votre panier est vide',
    'shop.subtitle':       'Représentez la culture de Bangui',
    'shop.freeShipping':   'Livraison gratuite à Bangui pour toute commande supérieure à 50 000 XAF',
    'shop.limitedEdition': 'Édition Limitée',

    /* Contact */
    'contact.title':       'Contact',
    'contact.name':        'Votre nom',
    'contact.email':       'Votre email',
    'contact.phone':       'Votre téléphone',
    'contact.subject':     'Sujet',
    'contact.message':     'Message',
    'contact.send':        'Envoyer le message',
    'contact.sent':        'Message envoyé !',

    /* Hero stats */
    'hero.stats.events':     'Événements / mois',
    'hero.stats.restaurants':'Restaurants',
    'hero.stats.followers':  'Followers',
    'hero.scroll':           'Défiler',

    /* Cinema */
    'cinema.title':          'Cinéma & Culture',
    'cinema.subtitle':       'Films, concerts, expositions et théâtre à Bangui',
    'cinema.arts':           'Arts & Spectacles',
    'cinema.nowScreening':   'À l\'écran',
    'cinema.nowPlaying':     'Films à l\'affiche',
    'cinema.agenda':         'Agenda',
    'cinema.culturalAgenda': 'Agenda Culturel',
    'cinema.urbanArt':       'Art urbain',
    'cinema.urbanArtTitle':  'Art de rue à Bangui',

    /* Gallery */
    'gallery.video':         'Vidéo',
    'gallery.photo':         'Photo',
    'gallery.viewAll':       'Voir toute la galerie',

    /* Talents */
    'talent.exclusive':      'Interview Exclusive',
    'talent.watch':          'Voir l\'interview',
    'talent.learnMore':      'En savoir plus',

    /* Contact */
    'contact.contactUs':     'Nous contacter',
    'contact.response':      'On vous répond sous 24h',
    'contact.description':   'Une question, un partenariat ou une idée de collaboration ? Envoyez-nous un message !',
    'contact.whatsapp':      'WhatsApp',
    'contact.address':       'Adresse',
    'contact.telephone':     'Téléphone',
    'contact.thankYou':      'Nous vous répondrons dans les plus brefs délais.',
    'contact.sendAnother':   'Envoyer un autre message',
    'contact.subjectChoose': 'Choisir un sujet',
    'contact.sub.partnership':'Partenariat',
    'contact.sub.event':     'Événement',
    'contact.sub.advertising':'Publicité',
    'contact.sub.press':     'Presse',
    'contact.sub.other':     'Autre',

    /* Restaurants extras */
    'restaurants.nightlifeLabel':  'Guide Nightlife',
    'restaurants.nightlifeTitle':  'La nuit à Bangui',
    'restaurants.nightlifeSub':    'Les meilleures adresses nocturnes',
    'restaurants.view':            'Voir',

    /* Newsletter */
    'newsletter.join':             'Rejoignez la communauté',
    'newsletter.subscribed':       'Vous êtes abonné(e) ! Merci.',
    'newsletter.noSpam':           'Pas de spam. Désinscription possible à tout moment.',
    'newsletter.success':          'Merci pour votre abonnement !',
    'newsletter.error':            'Erreur. Réessayez.',
    'newsletter.stat.events':      'Événements / mois',
    'newsletter.stat.restaurants': 'Restaurants référencés',
    'newsletter.stat.articles':    'Articles publiés',
    'newsletter.stat.members':     'Membres communauté',

    /* Partners */
    'partners.title':              'Nos partenaires',

    /* Cart / Checkout */
    'cart.clear':             'Vider',
    'cart.discoverShop':      'Découvrez notre boutique',
    'cart.explore':           'Explorer',
    'cart.sizeLabel':         'Taille',
    'cart.colorLabel':        'Couleur',
    'cart.subtotal':          'Sous-total',
    'cart.shipping':          'Livraison',
    'cart.freeShipping':      'Gratuite',
    'cart.order':             'Commander',
    'cart.yourOrder':         'Votre commande',
    'cart.checkoutInfo':      'Renseignez vos informations de contact pour finaliser votre commande. Vous recevrez une confirmation par email.',
    'cart.fullName':          'Nom complet',
    'cart.phoneLabel':        'Téléphone',
    'cart.addressLabel':      'Adresse de livraison',
    'cart.optional':          'optionnel',
    'cart.summary':           'Récapitulatif',
    'cart.processing':        'Traitement...',
    'cart.confirmOrder':      'Confirmer la commande',
    'cart.emailConfirmation': 'Un email de confirmation vous sera envoyé automatiquement.',
    'cart.confirmed':         'Commande confirmée !',
    'cart.thankYou':          'Merci pour votre commande.',
    'cart.confirmationSentTo':'Un email de confirmation a été envoyé à',
    'cart.teamContact':       'Notre équipe vous contactera pour la livraison.',
    'cart.continueShopping':  'Continuer mes achats',
    'cart.required':          'Nom, téléphone et email sont requis',
    'cart.orderSuccess':      'Commande passée avec succès !',

    /* Discover */
    'discover.guide':           'Guide de voyage',
    'discover.subtitle':        'Votre guide complet pour explorer la capitale de la République Centrafricaine',
    'discover.neighborhoods':   'Quartiers',
    'discover.neighborhoodsTrending': 'Quartiers tendance',
    'discover.photography':     'Photographie',
    'discover.photoSpots':      'Meilleurs spots photo',
    'discover.guides.todo':     'Que faire à Bangui',
    'discover.guides.eat':      'Où manger',
    'discover.guides.nightlife':'Nightlife',
    'discover.guides.photoSpots':'Best Photo Spots',
    'discover.guides.todo.desc':'Les incontournables de la capitale centrafricaine.',
    'discover.guides.eat.desc': 'Les meilleures tables de Bangui.',
    'discover.guides.nightlife.desc': 'Bars, clubs et soirées inoubliables.',
    'discover.guides.photo.desc': 'Les plus beaux endroits à photographier.',
    'discover.neighborhood.downtown': 'Centre-ville',
    'discover.neighborhood.downtown.desc': 'Le cœur battant de Bangui, commerces et administrations.',
    'discover.neighborhood.boyrabe': 'Boy-Rabe',
    'discover.neighborhood.boyrabe.desc': 'Quartier animé, marché populaire et vie de quartier authentique.',
    'discover.neighborhood.residential': 'Quartier Résidentiel',
    'discover.neighborhood.residential.desc': 'Les villas et restaurants gastronomiques de Bangui.',
    'discover.neighborhood.lakouanga': 'Lakouanga',
    'discover.neighborhood.lakouanga.desc': 'Bord de fleuve, pêcheurs et couchers de soleil spectaculaires.',

    /* Practical */
    'practical.guide':    'Guide du voyageur',
    'practical.title':    'Informations Pratiques',
    'practical.subtitle': 'Tout ce qu\'il faut savoir avant de venir à Bangui',
    'practical.emergency':'Numéros d\'urgence',

    /* Lifestyle */
    'lifestyle.readTime': 'min de lecture',

    /* Auth */
    'auth.login':          'Se connecter',
    'auth.register':       'S\'inscrire',
    'auth.logout':         'Se déconnecter',
    'auth.email':          'Email',
    'auth.password':       'Mot de passe',
    'auth.name':           'Nom complet',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.loginSubtitle':  'Connectez-vous à votre compte',
    'auth.noAccount':      'Pas encore de compte ?',
    'auth.tagline':        'Le meilleur de Bangui vous attend.',

    /* Navbar extras */
    'nav.announcement':          '✦ Le meilleur de Bangui — Événements · Restaurants · Culture · Nightlife ✦',
    'nav.discover.todo':         'Que faire à Bangui',
    'nav.discover.eat':          'Où manger',
    'nav.discover.nightlife':    'Nightlife',
    'nav.discover.neighborhoods':'Quartiers tendance',
    'nav.discover.photos':       'Meilleures photos',
    'nav.theme.light':           'Clair',
    'nav.theme.dark':            'Sombre',
    'nav.admin.link':            'Dashboard Admin',
    'nav.logout':                'Déconnexion',
    'nav.search.placeholder':    'Rechercher événements, restaurants, articles...',
    'nav.search.resultsFor':     'Recherche pour',
    'nav.search.ariaLabel':      'Rechercher',
    'nav.cart.ariaLabel':        'Panier',
    'nav.theme.ariaLabel':       'Thème',

    /* Footer */
    'footer.tagline':         'La référence lifestyle de Bangui. Événements, restaurants, culture et nightlife en République Centrafricaine.',
    'footer.newsletter.subscribed': '✓ Merci ! Vous êtes abonné(e).',
    'footer.columns.explore': 'Explorer',
    'footer.columns.info':    'Infos pratiques',
    'footer.columns.shop':    'Boutique',
    'footer.columns.legal':   'Informations',
    'footer.links.hotels':    'Hôtels & Séjours',
    'footer.links.transport': 'Transport',
    'footer.links.safety':    'Sécurité',
    'footer.links.visa':      'Visa & Aéroport',
    'footer.links.tshirts':   'T-Shirts',
    'footer.links.accessories':'Accessoires',
    'footer.links.limitedEditions':'Éditions Limitées',
    'footer.links.legal':     'Mentions légales',
    'footer.links.privacy':   'Confidentialité',
    'footer.links.terms':     'CGV',
    'footer.links.partners':  'Partenaires',
    'footer.made':            'Fait avec ♥ à Bangui',
    'footer.contact.location':'Bangui, République Centrafricaine',
    'footer.rights':       '© 2025 Bangui est Doux. Tous droits réservés.',
    'footer.newsletter':   'Newsletter',
    'footer.follow':       'Nous suivre',

    /* Admin nav */
    'admin.nav.dashboard':   'Tableau de bord',
    'admin.nav.events':      'Événements',
    'admin.nav.restaurants': 'Restaurants',
    'admin.nav.articles':    'Articles',
    'admin.nav.cinema':      'Cinéma & Culture',
    'admin.nav.talents':     'Talents',
    'admin.nav.gallery':     'Galerie',
    'admin.nav.shop':        'Boutique',
    'admin.nav.orders':      'Commandes',
    'admin.nav.partners':      'Partenaires',
    'admin.nav.hotels':        'Hôtels',
    'admin.nav.hotelBookings': 'Réservations Hôtel',
    'admin.nav.cars':          'Voitures',
    'admin.nav.carRentals':    'Locations Voiture',
    'admin.nav.users':         'Utilisateurs',
    'admin.nav.messages':      'Messages',
    'admin.nav.analytics':     'Analytiques',
    'admin.nav.settings':      'Paramètres',
    'admin.nav.viewSite':    'Voir le site',
    'admin.nav.logout':      'Déconnexion',

    /* Admin header */
    'admin.header.search':   'Rechercher...',
    'admin.header.subtitle': 'Bangui est Doux · CMS',

    /* Admin login */
    'admin.login.title':    'Espace administration',
    'admin.login.email':    'Email',
    'admin.login.password': 'Mot de passe',
    'admin.login.submit':   'Se connecter',
    'admin.login.loading':  'Connexion...',
    'admin.login.denied':   'Accès refusé – droits administrateur requis',

    /* Admin dashboard */
    'admin.dash.greeting':  'Bonjour',
    'admin.dash.visitors':  'Visiteurs ce mois',
    'admin.dash.events':    'Événements actifs',
    'admin.dash.orders':    'Commandes',
    'admin.dash.pending':   'En attente',
    'admin.dash.restaurants':'Restaurants',
    'admin.dash.revenue':   'Revenus',
    'admin.dash.quickActions':'Actions rapides',
    'admin.dash.traffic':   'Trafic du site',
    'admin.dash.recentOrders':'Commandes récentes',
    'admin.dash.seeAll':    'Voir tout',
    'admin.dash.noOrders':  'Aucune commande pour l\'instant',
    'admin.theme.light':    'Mode clair',
    'admin.theme.dark':     'Mode sombre',
    'admin.lang.switch':    'English',
  },
  en: {
    /* Nav */
    'nav.home':         'Home',
    'nav.events':       'Events',
    'nav.restaurants':  'Restaurants & Nightlife',
    'nav.cinema':       'Cinema & Culture',
    'nav.discover':     'Discover Bangui',
    'nav.practical':    'Practical Info',
    'nav.hotels':       'Hotels',
    'nav.cars':         'Car Rental',
    'nav.talents':      'Talents & Inspirations',
    'nav.gallery':      'Gallery',
    'nav.shop':         'Shop',
    'nav.contact':      'Contact',
    'nav.admin':        'Admin',

    /* Home hero */
    'hero.tagline':     'The Best of Bangui',
    'hero.subtitle':    'Events, restaurants, culture and nightlife in Bangui, Central African Republic',
    'hero.cta.discover':'Discover Bangui',
    'hero.cta.events':  'Explore Events',
    'hero.cta.book':    'Book an Experience',

    /* Sections */
    'section.events.title':      'Upcoming Events',
    'section.events.subtitle':   "Don't miss a thing",
    'section.restaurants.title': 'Restaurants & Nightlife',
    'section.restaurants.subtitle': "Bangui's best addresses",
    'section.talents.title':     'Talents & Inspirations',
    'section.talents.subtitle':  "Meet Bangui's personalities",
    'section.gallery.title':     'Gallery',
    'section.gallery.subtitle':  'The best moments',
    'section.articles.title':    'Latest Articles',
    'section.articles.subtitle': 'Discover our magazine',
    'section.newsletter.title':  'Stay Connected',
    'section.newsletter.subtitle':'Get our best recommendations',
    'section.newsletter.cta':    'Subscribe',
    'section.newsletter.placeholder': 'Your email',

    /* General */
    'general.noContent':  'No content available',
    'general.comingSoon': 'Check back soon for new content',
    'general.seeAll':     'See all',
    'general.learnMore':  'Learn more',
    'general.bookNow':    'Book now',
    'general.loading':    'Loading...',
    'general.error':      'An error occurred',
    'general.noResults':  'No results',
    'general.free':       'Free',
    'general.from':       'From',
    'general.at':         'at',
    'general.by':         'by',
    'general.on':         'on',
    'general.in':         'in',
    'general.readMore':   'Read more',
    'general.share':      'Share',
    'general.filter':     'Filter',
    'general.all':        'All',
    'general.featured':   'Featured',
    'general.new':        'New',
    'general.sold_out':   'Sold out',
    'general.limited':    'Limited edition',
    'general.save':       'Save',
    'general.cancel':     'Cancel',
    'general.delete':     'Delete',
    'general.edit':       'Edit',
    'general.add':        'Add',
    'general.search':     'Search',
    'general.close':      'Close',
    'general.back':       'Back',
    'general.next':       'Next',
    'general.prev':       'Prev',
    'general.submit':     'Submit',
    'general.confirm':    'Confirm',
    'general.success':    'Success!',

    /* Events */
    'events.title':        'Events',
    'events.category.all': 'All',
    'events.rsvp':         'RSVP',
    'events.tickets':      'Tickets',
    'events.countdown':    'Countdown',
    'events.past':         'Past event',
    'events.today':        'Today',
    'events.search':       'Search for an event...',
    'events.found':        'event(s) found',

    /* Category filters */
    'cat.all':              'All',
    'cat.concerts':         'Concerts',
    'cat.festivals':        'Festivals',
    'cat.cinema':           'Cinema',
    'cat.poolParties':      'Pool Parties',
    'cat.jazzNights':       'Jazz Nights',
    'cat.sports':           'Sports',
    'cat.exhibitions':      'Exhibitions',
    'cat.restaurantOpenings':'Restaurants',
    'cat.restaurant':       'Restaurants',
    'cat.bar':              'Bars',
    'cat.rooftop':          'Rooftops',
    'cat.lounge':           'Lounges',
    'cat.nightclub':        'Nightlife',
    'cat.cafe':             'Cafés',
    'cat.streetFood':       'Street Food',
    'cat.fastFood':         'Fast Food',
    'cat.tshirts':          'T-Shirts',
    'cat.caps':             'Caps',
    'cat.toteBags':         'Tote Bags',
    'cat.glassware':        'Glassware',
    'cat.accessories':      'Accessories',
    'cat.limitedEditions':  'Limited Editions',
    'cat.events':           'Events',
    'cat.food':             'Gastronomy',
    'cat.culture':          'Culture',
    'cat.video':            'Videos',
    'cat.artist':           'Artists',
    'cat.musician':         'Musicians',
    'cat.entrepreneur':     'Entrepreneurs',
    'cat.influencer':       'Influencers',
    'cat.chef':             'Chefs',
    'cat.creator':          'Creators',

    /* Restaurants */
    'restaurants.reserve':    'Reserve a table',
    'restaurants.hours':      'Hours',
    'restaurants.menu':       'Menu',
    'restaurants.gallery':    'Photos',
    'restaurants.reviews':    'Reviews',
    'restaurants.call':       'Call',
    'restaurants.directions': 'Directions',
    'restaurants.search':     'Search for a restaurant...',
    'restaurants.allAddresses':'All addresses',

    /* Shop */
    'shop.cart':           'Cart',
    'shop.addToCart':      'Add to cart',
    'shop.checkout':       'Checkout',
    'shop.total':          'Total',
    'shop.quantity':       'Quantity',
    'shop.size':           'Size',
    'shop.color':          'Color',
    'shop.empty':          'Your cart is empty',
    'shop.subtitle':       'Represent Bangui culture',
    'shop.freeShipping':   'Free delivery in Bangui for orders over 50,000 XAF',
    'shop.limitedEdition': 'Limited Edition',

    /* Contact */
    'contact.title':       'Contact',
    'contact.name':        'Your name',
    'contact.email':       'Your email',
    'contact.phone':       'Your phone',
    'contact.subject':     'Subject',
    'contact.message':     'Message',
    'contact.send':        'Send message',
    'contact.sent':        'Message sent!',

    /* Hero stats */
    'hero.stats.events':     'Events / month',
    'hero.stats.restaurants':'Restaurants',
    'hero.stats.followers':  'Followers',
    'hero.scroll':           'Scroll',

    /* Cinema */
    'cinema.title':          'Cinema & Culture',
    'cinema.subtitle':       'Films, concerts, exhibitions and theatre in Bangui',
    'cinema.arts':           'Arts & Entertainment',
    'cinema.nowScreening':   'Now Screening',
    'cinema.nowPlaying':     'Now Playing',
    'cinema.agenda':         'Agenda',
    'cinema.culturalAgenda': 'Cultural Agenda',
    'cinema.urbanArt':       'Urban Art',
    'cinema.urbanArtTitle':  'Street Art in Bangui',

    /* Gallery */
    'gallery.video':         'Video',
    'gallery.photo':         'Photo',
    'gallery.viewAll':       'View full gallery',

    /* Talents */
    'talent.exclusive':      'Exclusive Interview',
    'talent.watch':          'Watch interview',
    'talent.learnMore':      'Learn more',

    /* Contact */
    'contact.contactUs':     'Contact us',
    'contact.response':      'We respond within 24h',
    'contact.description':   'A question, a partnership or a collaboration idea? Send us a message!',
    'contact.whatsapp':      'WhatsApp',
    'contact.address':       'Address',
    'contact.telephone':     'Phone',
    'contact.thankYou':      'We will get back to you as soon as possible.',
    'contact.sendAnother':   'Send another message',
    'contact.subjectChoose': 'Choose a subject',
    'contact.sub.partnership':'Partnership',
    'contact.sub.event':     'Event',
    'contact.sub.advertising':'Advertising',
    'contact.sub.press':     'Press',
    'contact.sub.other':     'Other',

    /* Restaurants extras */
    'restaurants.nightlifeLabel':  'Nightlife Guide',
    'restaurants.nightlifeTitle':  'Bangui by Night',
    'restaurants.nightlifeSub':    'The best nighttime venues',
    'restaurants.view':            'View',

    /* Newsletter */
    'newsletter.join':             'Join the community',
    'newsletter.subscribed':       'You are subscribed! Thank you.',
    'newsletter.noSpam':           'No spam. Unsubscribe at any time.',
    'newsletter.success':          'Thank you for subscribing!',
    'newsletter.error':            'Error. Please try again.',
    'newsletter.stat.events':      'Events / month',
    'newsletter.stat.restaurants': 'Listed restaurants',
    'newsletter.stat.articles':    'Articles published',
    'newsletter.stat.members':     'Community members',

    /* Partners */
    'partners.title':              'Our partners',

    /* Cart / Checkout */
    'cart.clear':             'Clear',
    'cart.discoverShop':      'Discover our shop',
    'cart.explore':           'Explore',
    'cart.sizeLabel':         'Size',
    'cart.colorLabel':        'Color',
    'cart.subtotal':          'Subtotal',
    'cart.shipping':          'Shipping',
    'cart.freeShipping':      'Free',
    'cart.order':             'Order',
    'cart.yourOrder':         'Your order',
    'cart.checkoutInfo':      'Enter your contact information to complete your order. You will receive a confirmation email.',
    'cart.fullName':          'Full name',
    'cart.phoneLabel':        'Phone',
    'cart.addressLabel':      'Delivery address',
    'cart.optional':          'optional',
    'cart.summary':           'Summary',
    'cart.processing':        'Processing...',
    'cart.confirmOrder':      'Confirm order',
    'cart.emailConfirmation': 'A confirmation email will be sent automatically.',
    'cart.confirmed':         'Order confirmed!',
    'cart.thankYou':          'Thank you for your order.',
    'cart.confirmationSentTo':'A confirmation email has been sent to',
    'cart.teamContact':       'Our team will contact you for delivery.',
    'cart.continueShopping':  'Continue shopping',
    'cart.required':          'Name, phone and email are required',
    'cart.orderSuccess':      'Order placed successfully!',

    /* Discover */
    'discover.guide':           'Travel Guide',
    'discover.subtitle':        'Your complete guide to exploring the capital of the Central African Republic',
    'discover.neighborhoods':   'Neighborhoods',
    'discover.neighborhoodsTrending': 'Trending neighborhoods',
    'discover.photography':     'Photography',
    'discover.photoSpots':      'Best photo spots',
    'discover.guides.todo':     'Things to do in Bangui',
    'discover.guides.eat':      'Where to eat',
    'discover.guides.nightlife':'Nightlife',
    'discover.guides.photoSpots':'Best Photo Spots',
    'discover.guides.todo.desc':'The must-see highlights of the Central African capital.',
    'discover.guides.eat.desc': "Bangui's best restaurants.",
    'discover.guides.nightlife.desc': 'Bars, clubs and unforgettable nights.',
    'discover.guides.photo.desc': 'The most beautiful places to photograph.',
    'discover.neighborhood.downtown': 'Downtown',
    'discover.neighborhood.downtown.desc': "Bangui's beating heart — shops and administration.",
    'discover.neighborhood.boyrabe': 'Boy-Rabe',
    'discover.neighborhood.boyrabe.desc': 'Lively neighborhood, popular market and authentic local life.',
    'discover.neighborhood.residential': 'Residential Area',
    'discover.neighborhood.residential.desc': "Bangui's villas and gourmet restaurants.",
    'discover.neighborhood.lakouanga': 'Lakouanga',
    'discover.neighborhood.lakouanga.desc': 'Riverside, fishermen and spectacular sunsets.',

    /* Practical */
    'practical.guide':    "Traveler's guide",
    'practical.title':    'Practical Information',
    'practical.subtitle': 'Everything you need to know before visiting Bangui',
    'practical.emergency':'Emergency Numbers',

    /* Lifestyle */
    'lifestyle.readTime': 'min read',

    /* Auth */
    'auth.login':          'Login',
    'auth.register':       'Sign up',
    'auth.logout':         'Logout',
    'auth.email':          'Email',
    'auth.password':       'Password',
    'auth.name':           'Full name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loginSubtitle':  'Sign in to your account',
    'auth.noAccount':      "Don't have an account?",
    'auth.tagline':        'The best of Bangui awaits you.',

    /* Navbar extras */
    'nav.announcement':          '✦ The Best of Bangui — Events · Restaurants · Culture · Nightlife ✦',
    'nav.discover.todo':         'Things to do in Bangui',
    'nav.discover.eat':          'Where to eat',
    'nav.discover.nightlife':    'Nightlife',
    'nav.discover.neighborhoods':'Trendy neighborhoods',
    'nav.discover.photos':       'Best photos',
    'nav.theme.light':           'Light',
    'nav.theme.dark':            'Dark',
    'nav.admin.link':            'Admin Dashboard',
    'nav.logout':                'Logout',
    'nav.search.placeholder':    'Search events, restaurants, articles...',
    'nav.search.resultsFor':     'Search for',
    'nav.search.ariaLabel':      'Search',
    'nav.cart.ariaLabel':        'Cart',
    'nav.theme.ariaLabel':       'Theme',

    /* Footer */
    'footer.tagline':         "Bangui's lifestyle reference. Events, restaurants, culture and nightlife in the Central African Republic.",
    'footer.newsletter.subscribed': "✓ Thanks! You're subscribed.",
    'footer.columns.explore': 'Explore',
    'footer.columns.info':    'Practical info',
    'footer.columns.shop':    'Shop',
    'footer.columns.legal':   'Information',
    'footer.links.hotels':    'Hotels & Stays',
    'footer.links.transport': 'Transport',
    'footer.links.safety':    'Safety',
    'footer.links.visa':      'Visa & Airport',
    'footer.links.tshirts':   'T-Shirts',
    'footer.links.accessories':'Accessories',
    'footer.links.limitedEditions':'Limited Editions',
    'footer.links.legal':     'Legal notice',
    'footer.links.privacy':   'Privacy',
    'footer.links.terms':     'Terms',
    'footer.links.partners':  'Partners',
    'footer.made':            'Made with ♥ in Bangui',
    'footer.contact.location':'Bangui, Central African Republic',
    'footer.rights':       '© 2025 Bangui est Doux. All rights reserved.',
    'footer.newsletter':   'Newsletter',
    'footer.follow':       'Follow us',

    /* Admin nav */
    'admin.nav.dashboard':   'Dashboard',
    'admin.nav.events':      'Events',
    'admin.nav.restaurants': 'Restaurants',
    'admin.nav.articles':    'Articles',
    'admin.nav.cinema':      'Cinema & Culture',
    'admin.nav.talents':     'Talents',
    'admin.nav.gallery':     'Gallery',
    'admin.nav.shop':        'Shop',
    'admin.nav.orders':      'Orders',
    'admin.nav.partners':      'Partners',
    'admin.nav.hotels':        'Hotels',
    'admin.nav.hotelBookings': 'Hotel Bookings',
    'admin.nav.cars':          'Cars',
    'admin.nav.carRentals':    'Car Rentals',
    'admin.nav.users':         'Users',
    'admin.nav.messages':      'Messages',
    'admin.nav.analytics':     'Analytics',
    'admin.nav.settings':    'Settings',
    'admin.nav.viewSite':    'View site',
    'admin.nav.logout':      'Logout',

    /* Admin header */
    'admin.header.search':   'Search...',
    'admin.header.subtitle': 'Bangui est Doux · CMS',

    /* Admin login */
    'admin.login.title':    'Administration panel',
    'admin.login.email':    'Email',
    'admin.login.password': 'Password',
    'admin.login.submit':   'Sign in',
    'admin.login.loading':  'Signing in...',
    'admin.login.denied':   'Access denied – admin rights required',

    /* Admin dashboard */
    'admin.dash.greeting':  'Hello',
    'admin.dash.visitors':  'Visitors this month',
    'admin.dash.events':    'Active events',
    'admin.dash.orders':    'Orders',
    'admin.dash.pending':   'Pending',
    'admin.dash.restaurants':'Restaurants',
    'admin.dash.revenue':   'Revenue',
    'admin.dash.quickActions':'Quick actions',
    'admin.dash.traffic':   'Site traffic',
    'admin.dash.recentOrders':'Recent orders',
    'admin.dash.seeAll':    'See all',
    'admin.dash.noOrders':  'No orders yet',
    'admin.theme.light':    'Light mode',
    'admin.theme.dark':     'Dark mode',
    'admin.lang.switch':    'Français',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr');

  useEffect(() => {
    const saved = storage.get('bed_lang') as Lang | null;
    if (saved === 'fr' || saved === 'en') setLangState(saved);
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    storage.set('bed_lang', l);
    document.documentElement.lang = l;
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] ?? translations['en'][key] ?? key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
