require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const supabase = require('../config/supabase');
const Article    = require('../models/Article');
const Gallery    = require('../models/Gallery');
const Talent     = require('../models/Talent');
const Product    = require('../models/Product');
const User       = require('../models/User');

const mongoose2 = require('mongoose');
const partnerSchema = new mongoose2.Schema({ name: String, logo: String, website: String, category: String, isFeatured: { type: Boolean, default: false } }, { timestamps: true });
const Partner = mongoose2.models.Partner || mongoose2.model('Partner', partnerSchema);

/* ── Unsplash image helpers ──────────────────────── */
const IMG = {
  concert:    'https://images.unsplash.com/photo-1540039155733-5bb30b4f5e62?w=800',
  festival:   'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
  pool:       'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
  jazz:       'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
  sport:      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
  art:        'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
  cinema:     'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
  restaurant: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
  bar:        'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
  rooftop:    'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800',
  lounge:     'https://images.unsplash.com/photo-1574634534894-89d7576c8259?w=800',
  cafe:       'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
  nightclub:  'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
  street:     'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
  africa1:    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
  africa2:    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
  africa3:    'https://images.unsplash.com/photo-1604537529428-15bcbeecfe4d?w=800',
  music:      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
  culture:    'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800',
  food:       'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
  food2:      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
  fashion:    'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
  tshirt:     'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
  cap:        'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
  tote:       'https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800',
  hoodie:     'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800',
  glass:      'https://images.unsplash.com/photo-1479908525999-13752b4f75a3?w=800',
  bracelet:   'https://images.unsplash.com/photo-1573408301185-9519f94816f4?w=800',
  person1:    'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800',
  person2:    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800',
  person3:    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800',
  person4:    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
  person5:    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800',
  person6:    'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=800',
};

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('✅ Connected to MongoDB');

  const admin = await User.findOne({ role: 'superadmin' });
  if (!admin) { console.error('❌ No admin user found. Run the server first to create the admin.'); process.exit(1); }
  const adminId = admin._id;

  /* ── Clean existing seeded data ─────────────────── */
  await Promise.all([
    Event.deleteMany({}),
    Restaurant.deleteMany({}),
    Article.deleteMany({}),
    Gallery.deleteMany({}),
    Talent.deleteMany({}),
    Product.deleteMany({}),
    Partner.deleteMany({}),
  ]);
  console.log('🗑  Cleared existing data');

  /* ══════════════════════════════════════════════════
     EVENTS
  ══════════════════════════════════════════════════ */
  const now = new Date();
  const d = (daysFromNow) => new Date(now.getTime() + daysFromNow * 86400000).toISOString().slice(0, 10);

  await Event.create([
    {
      title: 'Bangui Music Festival 2025',
      category: 'festivals',
      date: d(14),
      time: '18:00',
      location: 'Palais des Sports de Bangui',
      address: 'Avenue des Martyrs, Bangui',
      description: 'Le plus grand festival de musique de Bangui revient ! Trois jours de concerts, d\'artistes locaux et internationaux, de gastronomie et de culture centrafricaine. Une célébration unique de la musique africaine.',
      image: IMG.festival,
      ticketPrice: 5000,
      isFree: false,
      isFeatured: true,
      isPublished: true,
      capacity: 2000,
      tags: ['musique', 'festival', 'culture'],
      createdBy: adminId,
    },
    {
      title: 'Pool Party BED Summer',
      category: 'pool-parties',
      date: d(7),
      time: '14:00',
      location: 'Hôtel Ledger Plaza',
      address: 'Boulevard du Général de Gaulle, Bangui',
      description: 'La pool party incontournable de l\'été à Bangui. DJ sets, cocktails exotiques, ambiance tropicale. Dress code : blanc et or. Réservation obligatoire.',
      image: IMG.pool,
      ticketPrice: 10000,
      isFree: false,
      isFeatured: true,
      isPublished: true,
      capacity: 300,
      tags: ['pool party', 'summer', 'vip'],
      createdBy: adminId,
    },
    {
      title: 'Jazz Night au Rooftop',
      category: 'jazz-nights',
      date: d(3),
      time: '20:30',
      location: 'Rooftop Chez Laetitia',
      address: 'Quartier Malimaka, Bangui',
      description: 'Une soirée jazz intimiste au cœur de Bangui. Le trio de Jean-Baptiste Zomondo vous invite à une expérience musicale unique sous les étoiles centrafricaines.',
      image: IMG.jazz,
      ticketPrice: 3000,
      isFree: false,
      isFeatured: false,
      isPublished: true,
      capacity: 80,
      tags: ['jazz', 'rooftop', 'musique live'],
      createdBy: adminId,
    },
    {
      title: 'Tournoi de Football Bangui est Doux',
      category: 'sports',
      date: d(21),
      time: '09:00',
      location: 'Stade Barthélémy Boganda',
      address: 'Avenue Boganda, Bangui',
      description: 'Le premier tournoi de football organisé par Bangui est Doux. 8 équipes en compétition, ambiance festive, restauration sur place. Entrée libre pour les supporters.',
      image: IMG.sport,
      ticketPrice: 0,
      isFree: true,
      isFeatured: false,
      isPublished: true,
      capacity: 5000,
      tags: ['football', 'sport', 'compétition'],
      createdBy: adminId,
    },
    {
      title: 'Soirée Cinéma en Plein Air',
      category: 'cinema',
      date: d(10),
      time: '19:30',
      location: 'Jardin Botanique de Bangui',
      address: 'Avenue de l\'Indépendance, Bangui',
      description: 'Projection de films africains primés sous les étoiles. Cette semaine : "La Sirène du Missisippi" de Mahamat-Saleh Haroun. Bar et snacks disponibles.',
      image: IMG.cinema,
      ticketPrice: 2000,
      isFree: false,
      isFeatured: true,
      isPublished: true,
      capacity: 200,
      tags: ['cinéma', 'plein air', 'film africain'],
      createdBy: adminId,
    },
    {
      title: 'Exposition Art Contemporain Centrafricain',
      category: 'art',
      date: d(5),
      time: '10:00',
      location: 'Palais de la Renaissance',
      address: 'Place de la République, Bangui',
      description: 'Découvrez les œuvres de 15 artistes centrafricains contemporains. Peintures, sculptures, installations et photographies qui racontent l\'histoire et la modernité de la RCA.',
      image: IMG.art,
      ticketPrice: 1500,
      isFree: false,
      isFeatured: false,
      isPublished: true,
      capacity: 500,
      tags: ['art', 'exposition', 'culture'],
      createdBy: adminId,
    },
    {
      title: 'Concert Afrobeat – DJ Satellite',
      category: 'concerts',
      date: d(18),
      time: '22:00',
      location: 'Le Balafon Club',
      address: 'Quartier Sica 1, Bangui',
      description: 'Le DJ Satellite, star de l\'afrobeat centrafricain, revient sur scène pour une nuit explosive. Trois heures de set non-stop, invités surprise et ambiance garantie.',
      image: IMG.concert,
      ticketPrice: 7500,
      isFree: false,
      isFeatured: true,
      isPublished: true,
      capacity: 600,
      tags: ['afrobeat', 'concert', 'nightlife'],
      createdBy: adminId,
    },
    {
      title: 'Dégustation Gastronomique RCA',
      category: 'restaurant-openings',
      date: d(12),
      time: '19:00',
      location: 'Restaurant Le Relais des Chasses',
      address: 'Avenue Boganda, Bangui',
      description: 'Une soirée exclusive de dégustation de la cuisine centrafricaine traditionnelle et créative. Chefs locaux, vins sélectionnés, expérience gastronomique unique. Places très limitées.',
      image: IMG.food,
      ticketPrice: 25000,
      isFree: false,
      isFeatured: false,
      isPublished: true,
      capacity: 40,
      tags: ['gastronomie', 'dégustation', 'cuisine'],
      createdBy: adminId,
    },
  ]);
  console.log('✅ Events seeded (8)');

  /* ══════════════════════════════════════════════════
     RESTAURANTS
  ══════════════════════════════════════════════════ */
  await Restaurant.create([
    {
      name: 'Le Relais des Chasses',
      category: 'restaurant',
      description: 'Restaurant gastronomique au cœur de Bangui, spécialisé dans la cuisine centrafricaine traditionnelle revisitée. Cadre élégant, service impeccable, carte des vins exceptionnelle.',
      address: 'Avenue Boganda, Bangui',
      phone: '+236 75 23 45 67',
      email: 'contact@relais-chasses.cf',
      website: 'https://relais-chasses.cf',
      instagram: '@relais_chasses_bangui',
      image: IMG.restaurant,
      priceRange: 4,
      isFeatured: true,
      isPublished: true,
      tags: ['gastronomie', 'centrafricain', 'vip'],
      createdBy: adminId,
    },
    {
      name: 'Rooftop 360° – Ledger Plaza',
      category: 'rooftop',
      description: 'Le rooftop le plus exclusif de Bangui, au sommet du Ledger Plaza. Vue panoramique sur la ville et le fleuve Oubangui. Cocktails signatures, cuisine fusion et ambiance lounge.',
      address: 'Boulevard du Général de Gaulle, Bangui',
      phone: '+236 21 61 05 05',
      email: 'restaurant@ledger-bangui.com',
      website: 'https://ledger-bangui.com',
      instagram: '@ledger_bangui',
      image: IMG.rooftop,
      priceRange: 4,
      isFeatured: true,
      isPublished: true,
      tags: ['rooftop', 'vip', 'cocktails', 'vue panoramique'],
      createdBy: adminId,
    },
    {
      name: 'Chez Laetitia',
      category: 'lounge',
      description: 'Le spot branché de Bangui, entre resto chic et bar lounge. Cuisine afro-européenne, DJ les weekends, terrasse verdoyante. L\'adresse incontournable de la jet-set bangooise.',
      address: 'Quartier Malimaka, Bangui',
      phone: '+236 72 34 56 78',
      email: 'chezelaetitia@gmail.com',
      instagram: '@chez_laetitia_bgi',
      image: IMG.lounge,
      priceRange: 3,
      isFeatured: true,
      isPublished: true,
      tags: ['lounge', 'afro-européen', 'terrasse'],
      createdBy: adminId,
    },
    {
      name: 'Le Balafon',
      category: 'nightclub',
      description: 'La boîte de nuit emblématique de Bangui depuis 15 ans. Musique afrobeat, zouk, coupé-décalé. DJ résidents et artistes invités tous les weekends. Bar premium.',
      address: 'Quartier Sica 1, Bangui',
      phone: '+236 70 12 34 56',
      instagram: '@lebalafon_officiel',
      image: IMG.nightclub,
      priceRange: 2,
      isFeatured: false,
      isPublished: true,
      tags: ['nightclub', 'afrobeat', 'DJ'],
      createdBy: adminId,
    },
    {
      name: 'Café Central',
      category: 'cafe',
      description: 'Le café le plus animé du centre-ville. Petit-déjeuner centrafricain, sandwichs maison, jus de fruits frais. WiFi gratuit, espace de travail agréable. Ouvert de 7h à 22h.',
      address: 'Avenue des Martyrs, Bangui-Centre',
      phone: '+236 73 45 67 89',
      email: 'cafecentral.bgi@gmail.com',
      image: IMG.cafe,
      priceRange: 1,
      isFeatured: false,
      isPublished: true,
      tags: ['café', 'petit-déjeuner', 'wifi', 'travail'],
      createdBy: adminId,
    },
    {
      name: 'Street Food Kokoro',
      category: 'street-food',
      description: 'Le meilleur street food de Bangui. Brochettes de viande, poisson grillé, plantains frits, sauces maison. Ambiance authentique, prix abordables. Un must pour découvrir la vraie cuisine de rue.',
      address: 'Marché Central, Bangui',
      phone: '+236 75 67 89 01',
      image: IMG.street,
      priceRange: 1,
      isFeatured: false,
      isPublished: true,
      tags: ['street food', 'grillades', 'authentique', 'local'],
      createdBy: adminId,
    },
    {
      name: 'Le Bar de l\'Indépendance',
      category: 'bar',
      description: 'Bar iconique sur l\'avenue de l\'Indépendance. Bières locales et importées, cocktails tropicaux, happy hour de 17h à 19h. Retransmission des matchs de football. Terrasse animée.',
      address: 'Avenue de l\'Indépendance, Bangui',
      phone: '+236 71 23 45 67',
      instagram: '@bar_independance_bgi',
      image: IMG.bar,
      priceRange: 2,
      isFeatured: false,
      isPublished: true,
      tags: ['bar', 'happy hour', 'football', 'terrasse'],
      createdBy: adminId,
    },
    {
      name: 'M\'BOKA Restaurant',
      category: 'restaurant',
      description: 'Restaurant familial spécialisé dans les plats traditionnels centrafricains. Gombo, moambe, kwanga, ndolé. Recettes de grand-mère, ingrédients frais du marché. L\'âme de la cuisine centrafricaine.',
      address: 'Quartier KM5, Bangui',
      phone: '+236 77 89 01 23',
      image: IMG.africa1,
      priceRange: 2,
      isFeatured: true,
      isPublished: true,
      tags: ['centrafricain', 'traditionnel', 'familial', 'authentique'],
      createdBy: adminId,
    },
  ]);
  console.log('✅ Restaurants seeded (8)');

  /* ══════════════════════════════════════════════════
     ARTICLES
  ══════════════════════════════════════════════════ */
  await Article.create([
    {
      title: 'Les 10 adresses incontournables de Bangui en 2025',
      category: 'guide',
      excerpt: 'De la street food au restaurant gastronomique, en passant par les bars branchés et les rooftops, notre sélection des meilleures adresses où manger, boire et s\'amuser à Bangui.',
      content: `Bangui est en pleine effervescence culinaire et culturelle. La capitale centrafricaine surprend par la qualité et la diversité de ses adresses. Voici notre sélection exclusive des 10 spots à ne pas manquer en 2025.\n\n**1. Le Relais des Chasses** – Pour une expérience gastronomique haut de gamme...\n\n**2. Rooftop 360°** – La vue la plus spectaculaire de Bangui...\n\n**3. Chez Laetitia** – Le lounge où il faut être vu...\n\n**4. Café Central** – Le QG des créatifs et entrepreneurs...\n\n**5. Street Food Kokoro** – Pour découvrir l\'authenticité de Bangui...`,
      image: IMG.food2,
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['guide', 'restaurants', 'bonnes adresses'],
    },
    {
      title: 'Bangui by night : le guide de la nightlife centrafricaine',
      category: 'nightlife',
      excerpt: 'La nuit bangooise est unique en Afrique centrale. Entre clubs afrobeat, soirées privées et rooftops exclusifs, voici comment vivre la nightlife de Bangui comme un(e) local(e).',
      content: `Quand le soleil se couche sur l\'Oubangui, Bangui se transforme. La ville révèle une facette festive et moderne qui surprend les visiteurs. La nightlife bangooise mélange tradition africaine et modernité internationale.\n\nLes meilleurs spots pour la nuit se concentrent dans les quartiers Malimaka et Sica 1, où bars, clubs et lounges se succèdent dans une ambiance électrique...`,
      image: IMG.nightclub,
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['nightlife', 'clubs', 'bars', 'nuit'],
    },
    {
      title: 'La cuisine centrafricaine : voyage au cœur des saveurs',
      category: 'gastronomy',
      excerpt: 'Gombo, kwanga, poisson de l\'Oubangui, viandes de brousse... La cuisine centrafricaine est riche, généreuse et profondément ancrée dans la culture locale. Découverte.',
      content: `La gastronomie centrafricaine est un patrimoine culturel vivant. Portée par des ingrédients locaux exceptionnels et des techniques ancestrales, elle raconte l\'histoire d\'un peuple et d\'une terre...\n\nParmi les plats emblématiques : le moambe (ragoût de poule à la sauce graine), le makemba (banane plantain frite), le foufou (boule de manioc)...`,
      image: IMG.food,
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['gastronomie', 'cuisine', 'centrafricain', 'culture'],
    },
    {
      title: 'Talents émergents : la nouvelle scène artistique de Bangui',
      category: 'culture',
      excerpt: 'Une nouvelle génération d\'artistes centrafricains émerge et conquiert les scènes africaines et internationales. Rencontre avec les créateurs qui portent haut les couleurs de la RCA.',
      content: `Bangui bouillonne de créativité. Musiciens, plasticiens, designers, entrepreneurs... Une jeunesse centrafricaine talentueuse et ambitieuse redéfinit l\'image de la République Centrafricaine sur la scène mondiale.\n\nParmi eux, des musiciens qui fusionnent les rythmes traditionnels de la RCA avec l\'afrobeats et le hip-hop moderne...`,
      image: IMG.africa2,
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['talents', 'artistes', 'culture', 'musique'],
    },
    {
      title: 'Pool Parties & Lifestyle : l\'été à Bangui',
      category: 'lifestyle',
      excerpt: 'L\'été à Bangui rime avec pool parties, soirées festives et lifestyle tropical. Les hôtels de luxe et villas privées se transforment en havres de fraîcheur et de fête.',
      content: `Avec ses 27°C de température moyenne, Bangui est une ville qui vit au soleil. Et quand la chaleur monte, les Bangoois savent où aller : les pool parties. Ces rassemblements festifs autour d\'une piscine sont devenus un véritable phénomène social et culturel...\n\nDes hôtels 5 étoiles aux villas privées, chaque weekend offre son lot de pool parties plus glamour les unes que les autres...`,
      image: IMG.pool,
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['lifestyle', 'pool party', 'été', 'luxe'],
    },
    {
      title: 'Bangui est Doux : l\'histoire d\'une plateforme culturelle',
      category: 'news',
      excerpt: 'Comment Bangui est Doux est devenu la référence lifestyle de la RCA. L\'histoire d\'un projet né de la passion pour Bangui et d\'une vision pour valoriser la culture centrafricaine.',
      content: `Bangui est Doux est né d\'une conviction : la capitale centrafricaine méritait une vitrine digitale à la hauteur de son dynamisme culturel. Fondée par une équipe de jeunes Centrafricains passionnés, la plateforme s\'est imposée en quelques mois comme la référence du lifestyle à Bangui...\n\nAujourd\'hui, Bangui est Doux c\'est : des événements, des restaurants, une boutique, une galerie et bien plus...`,
      image: IMG.africa3,
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date(),
      author: adminId,
      tags: ['bangui est doux', 'plateforme', 'culture', 'RCA'],
    },
  ]);
  console.log('✅ Articles seeded (6)');

  /* ══════════════════════════════════════════════════
     GALLERY
  ══════════════════════════════════════════════════ */
  await Gallery.create([
    { title: 'Bangui Music Festival – Main Stage', type: 'image', url: IMG.festival, category: 'events', isFeatured: true, uploadedBy: adminId },
    { title: 'Pool Party Ledger Plaza', type: 'image', url: IMG.pool, category: 'nightlife', isFeatured: true, uploadedBy: adminId },
    { title: 'Jazz Night Rooftop', type: 'image', url: IMG.jazz, category: 'events', isFeatured: false, uploadedBy: adminId },
    { title: 'Street Food Bangui', type: 'image', url: IMG.street, category: 'food', isFeatured: true, uploadedBy: adminId },
    { title: 'Exposition Art Contemporain', type: 'image', url: IMG.art, category: 'culture', isFeatured: false, uploadedBy: adminId },
    { title: 'Nightlife à Bangui', type: 'image', url: IMG.nightclub, category: 'nightlife', isFeatured: true, uploadedBy: adminId },
    { title: 'Culture et Traditions RCA', type: 'image', url: IMG.africa1, category: 'culture', isFeatured: false, uploadedBy: adminId },
    { title: 'Gastronomie Centrafricaine', type: 'image', url: IMG.food2, category: 'food', isFeatured: false, uploadedBy: adminId },
    { title: 'Concert Afrobeat', type: 'image', url: IMG.concert, category: 'events', isFeatured: true, uploadedBy: adminId },
    { title: 'Bangui – Vue de nuit', type: 'image', url: IMG.africa2, category: 'culture', isFeatured: false, uploadedBy: adminId },
    {
      title: 'Bangui est Doux – Recap 2024',
      type: 'video',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail: IMG.festival,
      category: 'events',
      isFeatured: true,
      uploadedBy: adminId,
    },
    {
      title: 'Discover Bangui – Official Film',
      type: 'video',
      url: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
      thumbnail: IMG.africa3,
      category: 'culture',
      isFeatured: false,
      uploadedBy: adminId,
    },
  ]);
  console.log('✅ Gallery seeded (12)');

  /* ══════════════════════════════════════════════════
     TALENTS
  ══════════════════════════════════════════════════ */
  await Talent.create([
    {
      name: 'DJ Satellite',
      title: 'DJ & Producteur',
      titleFr: 'DJ & Producteur',
      category: 'musician',
      bio: 'DJ Satellite est le nom incontournable de la scène électronique et afrobeat centrafricaine. Avec plus de 10 ans de carrière, il a mixé dans les plus grands clubs d\'Afrique centrale et collaboré avec des artistes internationaux.',
      bioFr: 'DJ Satellite est le nom incontournable de la scène électronique et afrobeat centrafricaine.',
      image: IMG.person1,
      coverImage: IMG.concert,
      instagram: '@djsatellite_rca',
      facebook: 'djsatelliteofficiel',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      isFeatured: true,
      isPublished: true,
      tags: ['DJ', 'afrobeat', 'électronique'],
      createdBy: adminId,
    },
    {
      name: 'Amina Kotto',
      title: 'Artiste Plasticienne',
      titleFr: 'Artiste Plasticienne',
      category: 'artist',
      bio: 'Amina Kotto est une artiste plasticienne dont les œuvres mêlent tradition centrafricaine et art contemporain international. Ses tableaux ont été exposés à Paris, Dakar et Johannesburg.',
      bioFr: 'Artiste plasticienne dont les œuvres ont été exposées à Paris, Dakar et Johannesburg.',
      image: IMG.person5,
      coverImage: IMG.art,
      instagram: '@aminakotto_art',
      isFeatured: true,
      isPublished: true,
      tags: ['art', 'peinture', 'contemporain'],
      createdBy: adminId,
    },
    {
      name: 'Jean-Baptiste Zomondo',
      title: 'Musicien Jazz',
      titleFr: 'Musicien Jazz',
      category: 'musician',
      bio: 'Pianiste et compositeur, Jean-Baptiste Zomondo incarne la nouvelle scène jazz centrafricaine. Formé au Conservatoire de Paris, il revient à Bangui pour créer un jazz qui parle d\'Afrique au monde.',
      bioFr: 'Pianiste et compositeur, figure du jazz centrafricain.',
      image: IMG.person2,
      coverImage: IMG.jazz,
      instagram: '@jbzomondo',
      facebook: 'jeanbaptistezomondo',
      isFeatured: false,
      isPublished: true,
      tags: ['jazz', 'piano', 'composition'],
      createdBy: adminId,
    },
    {
      name: 'Stella BG',
      title: 'Influenceuse & Créatrice',
      titleFr: 'Influenceuse & Créatrice de Contenu',
      category: 'influencer',
      bio: 'Stella BG est la créatrice de contenu centrafricaine la plus suivie sur les réseaux sociaux. Mode, lifestyle, voyage : elle porte la culture de Bangui à travers le monde avec authenticité et élégance.',
      bioFr: 'Créatrice de contenu et ambassadrice du lifestyle bangoois.',
      image: IMG.person5,
      coverImage: IMG.fashion,
      instagram: '@stellabg_officiel',
      facebook: 'stellabgcreator',
      isFeatured: true,
      isPublished: true,
      tags: ['influenceuse', 'mode', 'lifestyle', 'réseaux sociaux'],
      createdBy: adminId,
    },
    {
      name: 'Marcus Domo',
      title: 'Entrepreneur & Visionnaire',
      titleFr: 'Entrepreneur',
      category: 'entrepreneur',
      bio: 'Marcus Domo est le fondateur de plusieurs startups tech à Bangui. Passionné par l\'innovation africaine, il œuvre pour faire de Bangui un hub numérique en Afrique centrale.',
      bioFr: 'Entrepreneur et fondateur de startups tech à Bangui.',
      image: IMG.person6,
      coverImage: IMG.africa3,
      instagram: '@marcusdomo_rca',
      isFeatured: false,
      isPublished: true,
      tags: ['entrepreneur', 'tech', 'innovation', 'startup'],
      createdBy: adminId,
    },
    {
      name: 'Chef Blessing',
      title: 'Chef Cuisinière',
      titleFr: 'Chef Cuisinière',
      category: 'chef',
      bio: 'Chef Blessing est la cheffe qui réinvente la cuisine centrafricaine pour le monde. Formée en France, revenue à Bangui avec des étoiles dans les yeux, elle sublime les saveurs locales dans son restaurant M\'BOKA.',
      bioFr: 'Cheffe qui réinvente la gastronomie centrafricaine.',
      image: IMG.person3,
      coverImage: IMG.food2,
      instagram: '@chefblessing_rca',
      isFeatured: false,
      isPublished: true,
      tags: ['chef', 'gastronomie', 'cuisine centrafricaine'],
      createdBy: adminId,
    },
  ]);
  console.log('✅ Talents seeded (6)');

  /* ══════════════════════════════════════════════════
     PRODUCTS
  ══════════════════════════════════════════════════ */
  await Product.create([
    {
      name: 'T-Shirt Bangui est Doux – Classic',
      description: 'Le t-shirt iconique de Bangui est Doux. 100% coton premium, coupe unisexe. Logo brodé en vert sur fond noir. Disponible en 6 tailles.',
      category: 't-shirts',
      price: 15000,
      comparePrice: 20000,
      images: [IMG.tshirt],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'Noir', hex: '#0A0A0A' }, { name: 'Blanc', hex: '#FFFFFF' }],
      stock: 50,
      isFeatured: true,
      isLimited: false,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Casquette BED Gold Edition',
      description: 'Casquette brodée édition spéciale. Logo Bangui est Doux en fil vert sur casquette noire. Réglable, taille unique. Streetwear africain chic.',
      category: 'caps',
      price: 12000,
      images: [IMG.cap],
      stock: 30,
      isFeatured: true,
      isLimited: true,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Tote Bag BED Premium',
      description: 'Tote bag en toile épaisse avec logo Bangui est Doux. Poignées renforcées, grande capacité. Design minimaliste, parfait pour le quotidien.',
      category: 'tote-bags',
      price: 8000,
      images: [IMG.tote],
      colors: [{ name: 'Naturel', hex: '#F5F0E8' }, { name: 'Noir', hex: '#0A0A0A' }],
      stock: 80,
      isFeatured: false,
      isLimited: false,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Hoodie BED Oversize Premium',
      description: 'Hoodie oversize en coton bio premium. Broderie BED sur la poitrine, fit streetwear. Chaud, confortable et stylé. Édition limitée.',
      category: 'limited-editions',
      price: 28000,
      comparePrice: 35000,
      images: [IMG.hoodie],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [{ name: 'Noir', hex: '#0A0A0A' }, { name: 'Vert', hex: '#30f824' }],
      stock: 15,
      isFeatured: true,
      isLimited: true,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Coffret Verrerie BED',
      description: 'Set de 4 verres gravés au laser avec le logo Bangui est Doux. Verre épais qualité premium. Idéal comme cadeau ou pour recevoir avec style.',
      category: 'glassware',
      price: 25000,
      comparePrice: 32000,
      images: [IMG.glass],
      stock: 20,
      isFeatured: true,
      isLimited: true,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Bracelet Bangui',
      description: 'Bracelet artisanal fabriqué à Bangui. Perles aux couleurs de la RCA, fermoir doré. Pièce unique, artisanat local soutenu.',
      category: 'accessories',
      price: 5000,
      images: [IMG.bracelet],
      colors: [{ name: 'Vert/Or', hex: '#30f824' }, { name: 'Noir/Or', hex: '#0A0A0A' }],
      stock: 100,
      isFeatured: false,
      isLimited: false,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'Pack Lifestyle BED',
      description: 'Le pack complet Bangui est Doux : T-Shirt Classic + Casquette + Tote Bag. Meilleure valeur, livraison offerte. Représente ta culture.',
      category: 'limited-editions',
      price: 35000,
      comparePrice: 47000,
      images: [IMG.tshirt],
      stock: 10,
      isFeatured: true,
      isLimited: true,
      isActive: true,
      createdBy: adminId,
    },
    {
      name: 'T-Shirt BED Bangui Nuit',
      description: 'T-shirt graphique édition nightlife. Illustration de la skyline de Bangui by night. Impression DTG haute définition. Coton 180g premium.',
      category: 't-shirts',
      price: 17500,
      images: [IMG.tshirt],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [{ name: 'Noir', hex: '#0A0A0A' }],
      stock: 25,
      isFeatured: false,
      isLimited: true,
      isActive: true,
      createdBy: adminId,
    },
  ]);
  console.log('✅ Products seeded (8)');

  /* ══════════════════════════════════════════════════
     PARTNERS
  ══════════════════════════════════════════════════ */
  await Partner.create([
    { name: 'Hôtel Ledger Plaza', logo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=200', website: 'https://ledger-bangui.com', category: 'sponsor', isFeatured: true },
    { name: 'MTN Centrafrique', logo: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200', website: 'https://mtn.cf', category: 'sponsor', isFeatured: true },
    { name: 'Air France', logo: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=200', website: 'https://airfrance.com', category: 'media', isFeatured: false },
    { name: 'Ambassade de France en RCA', logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200', website: 'https://cf.ambafrance.org', category: 'institution', isFeatured: false },
    { name: 'Ti-ï Festival', logo: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=200', website: '#', category: 'association', isFeatured: true },
    { name: 'Radio Ndeke Luka', logo: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=200', website: 'https://radiondekeluka.org', category: 'media', isFeatured: false },
  ]);
  console.log('✅ Partners seeded (6)');

  console.log('\n🎉 Seed complete! Database populated with dummy data.\n');
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
